name: transform XMI
on:
  push:
    paths:
      - "analysis_and_design/transformation_output/xmi_conceptual_model/ePO_CM.xml"
jobs:
  transform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      #      - name: get Saxon
      #        uses: wei/curl@v1.1.1
      #        with:
      #          args: -o saxon https://kumisystems.dl.sourceforge.net/project/saxon/Saxon-HE/10/Java/SaxonHE10-6J.zip

      #        run: |
      #          pwd
      #          sudo curl -o saxon.zip "https://kumisystems.dl.sourceforge.net/project/saxon/Saxon-HE/10/Java/SaxonHE10-6J.zip"

      - name: list files
        run: ls -l

      - name: unzip saxon
        run: sudo unzip saxon/saxon.zip

      - name: make model2owl dir
        run: |
          mkdir model2owl

      - name: get model2owl
        run: |
          git clone https://.:${{ secrets.GITHUB_TOKEN }}@github.com/OP-TED/model2owl.git model2owl
      #        uses: actions/checkout@v2
      #        with:
      #          repository: OP-TED/model2owl.git

      - name: what dir
        run: |
          pwd

      - name: list dir
        run: |
          ls -l

      - name: transform owl-core
        run: |
          java -jar saxon-he-10.6.jar -s:analysis_and_design/transformation_output/xmi_conceptual_model/ePO_CM.xml -xsl:model2owl/src/owl-core.xsl -o:analysis_and_design/transformation_output/owl_ontology/ePO_owl_core.rdf

      - name: see result
        run: |
          ls -l analysis_and_design/transformation_output/owl_ontology

      - name: commit results
        |
        git config --local user.email "action@github.com"
        git config --local user.name "github-actions"
        git status
        git add ePO_owl_core.rdf
#        if [-z "$(git status --porcelain)"]; then
#        echo "::set-output name=push::false"
#        else
        git commit -m "transformed owl core"
#        echo "::set-output name=push::true"
#        fi
#        shell: bash

      - name: Push changes
#        if: steps.commit.outputs.push == 'true'
        uses: ad-m/github-push-action@master
        with:
           github_token: ${{ secrets.GITHUB_TOKEN }}