name: transform XMI
on:
  push:
    paths:
      - "analysis_and_design/transformation_output/xmi_conceptual_model/ePO_CM.xml"
jobs:
  transform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
#      - name: get Saxon
#        uses: wei/curl@v1.1.1
#        with:
#          args: -o saxon https://kumisystems.dl.sourceforge.net/project/saxon/Saxon-HE/10/Java/SaxonHE10-6J.zip

#        run: |
#          pwd
#          sudo curl -o saxon.zip "https://kumisystems.dl.sourceforge.net/project/saxon/Saxon-HE/10/Java/SaxonHE10-6J.zip"

      - name: list files
        run: ls -l

      - name: unzip saxon
        run: sudo unzip saxon/saxon.zip

      - name: get model2owl
        uses: actions/checkout@v2
        with:
          repository: "https://github.com/OP-TED/model2owl.git"

